# Generated by Django 3.1.7 on 2021-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_film_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
