# Generated by Django 3.1.7 on 2021-05-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210503_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='WD1WrcL6ZYvkv7aaYTsVpHFJH2sud7gj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='QanFnnV8w6ysGu2WnrfiXvEJytVMW8bk', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='n7nJkuwd2PyTH7R75XjHwXK6ekVjrJg5', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='FilmLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_film_user', to=settings.AUTH_USER_MODEL)),
                ('likedfilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_film', to='mainapp.film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('disliked_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_film', to='mainapp.film')),
                ('disliked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_film_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
