# Generated by Django 3.1.7 on 2021-05-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210506_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created2',
            field=models.DateField(db_index=True, default='2021-5-7'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='BkkAKDQfQsNskkAJXjxnc21kh2wZFb6y', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='sCjnKNehQyLqs2anWqa637Fv', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='WMw4bicJuYB5uiXpJxnZ22L9aL1XhmvE', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='XWr9xJzWN6Kfas7cx9F3mdj8jVbPad3Z', max_length=32, null=True),
        ),
    ]
