# Generated by Django 3.1.7 on 2021-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20210509_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='DFEGGsn1GGWpZ8LejJDua3J8tSuzGk78', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='dP6bYWSbjHrTYmXdZDRRr6GM', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='kCQkb1dL6ce16Vmd1eytQZyJtMWaKvmt', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_created2',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='FBTDaResyvqjA3SdC1n4bRXqqk4WSy7V', max_length=32, null=True),
        ),
    ]
