# Generated by Django 3.1.7 on 2021-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20210509_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='HMATpX4kBXQ1SUNth8hZf5n8UFu1HWU4', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='qiv1hbu2PVwJ4i44mirsATMy', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='cwZt3izXQnX9ACcFHwxYyUeGLGiUmpXn', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='videoviewmodel',
            name='date_created2',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='2xV3TUtFuQyBpd8xt523nPCjXDe4ywzB', max_length=32, null=True),
        ),
    ]
