# Generated by Django 3.1.7 on 2021-05-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20210509_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_created_without_time',
            field=models.DateField(db_index=True, default='2021-5-1'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='Y38AgvPtgmKZwxLQ6HLaR5HZczSPii6W', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='vZ3f1qJY5pya8Pc5JhyYYPWE', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='BPFBPY9PmMxZaYhR5CdMxhF9ybXKyPqy', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='fv86XB5huVwEL1ZkARgxmD7TQEiWdrey', max_length=32, null=True),
        ),
    ]
