# Generated by Django 3.1.7 on 2021-05-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20210509_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='d9sUz39ZrKjPeNstcbQg7PVnnxmaheRD', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='YkX9Nzzafu4dQbEXewfz1ktK', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='tQQtVbNbYUDUy7mMnpg2yqujPJpxFhdF', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_created_without_time',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='W89fibzgiUSqmyy67nEL9PKAriKN4eT1', max_length=32, null=True),
        ),
    ]
