# Generated by Django 3.1.7 on 2021-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='Users avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Users banners/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='Videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_banner',
            field=models.ImageField(upload_to='Videos banners/'),
        ),
    ]
