# Generated by Django 3.1.7 on 2021-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210511_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='7HLLmtQLSv9jSCNuzGpFDw3qhenjC7Y4', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='1eUHVJhjMY5NBnvwEumj47jWbBVaHgui', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='X7Watm3JgRXyWqyVjbKmwGSd6he5XkFK', max_length=32, null=True),
        ),
    ]
