# Generated by Django 3.1.7 on 2021-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210511_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_created_without_time',
            field=models.DateField(db_index=True, default='2021-11-5'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='y9QH4vPqdMReRXECqSEWHe7dVZ48G3Sc', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='RdnpDFDG8FmraAEruztMAMWezzuu89Ym', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='vnKb2QH4DPHKiYQZE7KF9yrcjwFCSmHJ', max_length=32, null=True),
        ),
    ]
