# Generated by Django 3.1.7 on 2021-05-02 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_actor_film_filmactor_filmgenre_filmproducer_filmwriter_genre_producer_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_film', to='mainapp.film')),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
