# Generated by Django 3.1.7 on 2021-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210511_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='qHxjDCjpu8HnQ96KgnjP2r87vRRxAxGF', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created_without_time',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='U2ARWyG7wn5jEm1m79h2ykyW942tB3ec', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='qSNC8ViUvjkKLKSH4uccYDq59pFPByLr', max_length=32, null=True),
        ),
    ]
