# Generated by Django 3.1.7 on 2021-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210511_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='EBZ9DYwdhZnLhApznFLuyREwKmy6C7GG', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='95cqC9z6kVTgvA1cJCdXSDZtSfv6QuyN', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='2E2kXz961hSqpYmuguzGLhuQXnT7u8zU', max_length=32, null=True),
        ),
    ]
