# Generated by Django 3.1.7 on 2021-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_buyfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_poster',
            field=models.ImageField(default='avatars/default/default_avatar.png', upload_to='film_posters/'),
        ),
    ]
