# Generated by Django 3.1.7 on 2021-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210514_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='Q4fD3BDtTMwgwjgV1FwqrHTXjdY6mr8u', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='qGh4u8DqNmNZuvVQCn1ipz7giMsxkqFn', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='92hBNmUqkFnKHNhEKxHj8rgHzHncwvRk', max_length=32, null=True),
        ),
    ]
