# Generated by Django 3.1.7 on 2021-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_film_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_poster',
            field=models.ImageField(upload_to='film_posters/'),
        ),
    ]
