# Generated by Django 3.1.7 on 2021-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210514_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='7jB2c2B8Nxcx42TyRMYyeBHdg4Q94T5N', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='Uqj85YJWrKD4ZBfNEtQhzc2WcitMxWQB', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='EQEzy5gPNEcCP46skKGjF8GTe4kWNBNJ', max_length=32, null=True),
        ),
    ]
