# Generated by Django 3.1.7 on 2021-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210503_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='running_time',
            field=models.CharField(default='0:00', max_length=150),
        ),
    ]
