# Generated by Django 3.1.7 on 2021-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210514_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='REPYVaqpgEqPPAX9RKiMkbaGDkLLvPpx', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='AMJ9GpZ4uU3Sz11aRei58zYYp4xXvL2r', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='n59gU6qxgV5mM236TcCxwftGybjTB4ty', max_length=32, null=True),
        ),
    ]
