# Generated by Django 3.1.7 on 2021-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210514_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='9qC1TNKLzMKGUhzYEA3aWXwpfLRHf2cT', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='fMWmPYxj9RQvUEjSgsjMzDV4GmmJT7jJ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='wRt9N9g7CGBp6L6AZgaSEJruRR92A4ji', max_length=32, null=True),
        ),
    ]
