# Generated by Django 3.1.7 on 2021-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210514_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='znJkZTpp6BrcAfbTG5CULnNHwFD6jXdn', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='q6upUuwRxaxHTQBmRcvJu3wZiFeJX53e', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='HCfJK8m2sDfMN1QTi6FwT1ZF1ZGNvq2w', max_length=32, null=True),
        ),
    ]
