# Generated by Django 3.1.7 on 2021-05-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_film_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='main_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.genre'),
        ),
    ]
