# Generated by Django 3.1.7 on 2021-05-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_actor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='born',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
