# Generated by Django 3.1.7 on 2021-05-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_actor_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='born',
            field=models.DateField(),
        ),
    ]
