# Generated by Django 3.1.7 on 2021-05-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_actor_film_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='film_poster',
            new_name='photo',
        ),
    ]
