# Generated by Django 3.1.7 on 2021-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210503_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='CfR7VbDNt8XrHCcCs1HMxyAFhnmEQRid', max_length=32, null=True),
        ),
    ]
