# Generated by Django 3.1.7 on 2021-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_actor_actor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='actor_id',
            field=models.CharField(blank=True, default='Fjts81sPYvVQGnGRpcNhHdLnQrk9Jpu8', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='born',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='producer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='photo',
            field=models.ImageField(default='avatars/default/man.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='G9AxXiL28BRLWjj1eMUGzf4qqkW8PE1n', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='born',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
