# Generated by Django 3.1.7 on 2021-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210503_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='actor_id',
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='DnLhHQw2xCaDtynRdDw3rDR2BKgsQ4Hu', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='xfyWwrdf4SEfm2Zwm3i5NPFNmAdXGTrk', max_length=32, null=True),
        ),
    ]
