# Generated by Django 3.1.7 on 2021-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210503_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='born',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='writer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='photo',
            field=models.ImageField(default='avatars/default/man.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='5hBWVtwFr4gE8UZ8L6vAW59UJQxT3q18', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='aZqXT31whhpnVadBCrAARycSmjN6SXRP', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='yMrEWp3VNn9sf2F2hPEpzDaGAuttqqEG', max_length=32, null=True),
        ),
    ]
