# Generated by Django 3.1.7 on 2021-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20210503_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='born',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='born',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='born',
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='RW9sBJYMpVZCjabEiXvwFyAmSvR5N5Lv', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='9T4jcNVC1YRGmCkFVvVapQJ229cW6UDE', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='zsySbWr9P1uqKCynSbnECxJJWcAFACM2', max_length=32, null=True),
        ),
    ]
