# Generated by Django 3.1.7 on 2021-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20210506_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_comments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='8eumfxfxAfeEBNBiQ1sTF2RTrqhcY2Cw', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='Qe9NymSZ6Zh6cmsvdSXgcZLh8k98TXzq', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='urf5Mh58HTP9G9yWFK44yTfm1tVa9X17', max_length=32, null=True),
        ),
    ]
