# Generated by Django 3.1.7 on 2021-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20210506_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='all_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='CMQqf3JUCQ7DJ5DNXtMpWJGWKkDcBLQC', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='HzVegN8vLD1ECXhJGMbgZWmhT7AVMPyf', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='vJf8e3jXwQQSkMn2N57uRNeBAtihnFvy', max_length=32, null=True),
        ),
    ]
