# Generated by Django 3.1.7 on 2021-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20210506_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_posts_dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='all_posts_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='5dHFCU6HQcTBawESz2Ez738qniGGrTiq', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='q7Lq5DNFGMiqBVv1HDBh2W3F2cEgLjBZ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='3683MHLYs3D7qAzv5nyC5VU4WndduW9n', max_length=32, null=True),
        ),
    ]
