# Generated by Django 3.1.7 on 2021-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210509_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_created2',
        ),
        migrations.AddField(
            model_name='video',
            name='date_created2',
            field=models.DateField(db_index=True, default='2021-5-7'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='nKxDBNKH1NyDFu6Y2jJfLaehN4aQYmbN', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='H3NsNNHgFzcqg47kcxMkEBxY', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='RkgnzXG8ExNjXwdKu1XN4Pvam1AnHFuV', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='NS6Z3Jn8QcZpS6ysU7Kf2NtduKKXXE7Y', max_length=32, null=True),
        ),
    ]
