# Generated by Django 3.1.7 on 2021-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20210509_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date_created2',
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='h9iTMdVmyM7qSP2kP7tyMjgvueDp5JdP', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='uRH7AiFRk4YibqLKpfVwFVga', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='qWRs9hJZiBunGGHuWZJUV7wvsAvhfY7w', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='pS9i6uDA8NhHikEvj3Zg3HJLu5PEDh6m', max_length=32, null=True),
        ),
    ]
