# Generated by Django 3.1.7 on 2021-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20210509_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoviewmodel',
            name='date_created2',
            field=models.DateField(db_index=True, default='2021-5-7'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='aU2AUYGvGmqeBK5mYBcBJdJBDJ1CRTJ6', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='FpSxC2jQdhVWCxUMaNNCxcBc', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='NTDDjSxb2qGU9bvSgFehxG7q8GBxXnHm', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='EBfgbwFqr8KSPcwj3z5DERMd7nL33w2i', max_length=32, null=True),
        ),
    ]
