# Generated by Django 3.1.7 on 2021-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20210509_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='donat_text',
            field=models.CharField(blank=True, default='Support the author ❤️', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='w3qcEJB5u5shzQcYJLB4zzTDyWffp54b', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='kDgi8zJrYcJd4B5G6NKN6rs8', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='Fm9ZqFaHLEdZAKqDhWpWB1fnt12mtS5x', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='ELpPEMHapcRj39MQ3fXTbUdvpSVmNiEd', max_length=32, null=True),
        ),
    ]
