# Generated by Django 3.2.3 on 2021-05-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='LGXGVgMCUR5kicXeg3NaX8BBWwYWgHkq', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='g45RYxPTGq7BCmJrMLiQ1UAMG97DpRCQ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='qST2cdtDdkCUWeRVgPNzXN9rZwe1pkGZ', max_length=32, null=True),
        ),
    ]
