# Generated by Django 3.1.7 on 2021-05-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='naY1gjpnN3PdbWDN2QWT5CYR6tVkFNWY', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='a19ZLf3Up19tkxKf5UNmTNVe2uL79DN9', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='STmGXsvsk8bg3NauggqJCKzGyRK9K46Z', max_length=32, null=True),
        ),
    ]
