# Generated by Django 3.1.7 on 2021-05-19 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210518_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='pe1V4amn4yezBvrJuzcSNVwkmzNtfpjG', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='fc2QwAJx5W6qwKkweKjnxXvjtmjCD4bw', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='puzaUMTk26YXUQ2U7yYUtDY9LnYxKa3s', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(blank=True, max_length=32, null=True)),
                ('track', models.FileField(upload_to='tracks/')),
                ('track_poster', models.ImageField(upload_to='track_posters/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=1000000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_created_without_time', models.DateField(auto_now_add=True, db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
