# Generated by Django 3.1.7 on 2021-05-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210519_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='description',
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='XsrAzgSyKN5kwzWWdDcP6zLYqWbMGbQs', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='4HfhMaWyAG2aPttUUKFg5fFDKnaaEkjY', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='VmjDL1wzjS8NQkQesSeLC9LYhyrkQ3EN', max_length=32, null=True),
        ),
    ]
