# Generated by Django 3.1.7 on 2021-05-21 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210520_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_auditions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='auditions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.CharField(blank=True, default='BNTtbPEtf27RRVvWUF7yuKznZGTbc5zS', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.CharField(blank=True, default='xhKDiZ8553vfeiFx7d3EpFGif8TtwZTZ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, default='rFunupp9WQNpLPScDrMPAWu5WRqxYrFb', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='TrackListenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_created_without_time', models.DateField(auto_now_add=True, db_index=True)),
                ('listened_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_track', to='mainapp.track')),
                ('listening_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
